version: "3.8"
services:
  torapi:
    image: lifailon/torapi:latest
    container_name: TorAPI
    environment:
      - PORT=${PORT}
      - PROXY_ADDRESS=${PROXY_ADDRESS}
      - PROXY_PORT=${PROXY_PORT}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - torapi:/rotapi
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped

  kcu-base:
    &kcu-base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./result:/app/db
      - ./logs:/app/logs
    depends_on:
      - torapi

  kcu:
    <<: *kcu-base
    container_name: kcu-films
    command: poetry run python main.py
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json

  kcu-mult:
    <<: *kcu-base
    container_name: kcu-cartoons
    command: poetry run python main.py
    env_file:
      - .env.mult
    volumes:
      - ./config-mult.json:/app/config.json

volumes:
  torapi: