version: "3.8"
services:
  torapi:
    image: lifailon/torapi:latest
    container_name: TorAPI
    environment:
      - PORT=${PORT}
      - PROXY_ADDRESS=${PROXY_ADDRESS}
      - PROXY_PORT=${PROXY_PORT}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - torapi:/rotapi
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
  kcu:
    build:
      context: ./kcu
    command: poetry run python main.py
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./result:/app/db
      - ./logs:/app/logs
      - ./config.json:/app/config.json
    depends_on:
      - torapi
#  kcu-mult:
#    build:
#      context: ./kcu
#    command: bash -c "sleep 60 && poetry run python main.py"
#    restart: unless-stopped
#    env_file:
#      - .env.mult
#    environment:
#      - TZ=Europe/Moscow
#    volumes:
#      - ./result:/app/db
#      - ./logs:/app/logs
#      - ./config-mult.json:/app/config.json
#    depends_on:
#      - torapi
#      - kcu
volumes:
  torapi: